name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: |
          backend/package-lock.json
          client/package-lock.json
    
    - name: Install backend dependencies
      run: |
        cd backend
        npm ci --production
    
    - name: Install and build frontend
      run: |
        cd client
        npm ci
        npm run build
    
    - name: Deploy via DigitalOcean Console
      run: |
        echo "🚀 Deployment Instructions:"
        echo "1. Go to DigitalOcean Dashboard"
        echo "2. Open Console for droplet 167.172.66.203"
        echo "3. Run: cd /var/www/travelagency && git pull origin main"
        echo "4. Run: cd backend && npm install --production"
        echo "5. Run: cd ../client && npm install && npm run build"
        echo "6. Run: cd ../backend && pm2 restart travelagency-backend"
        echo "✅ Deployment Complete!"
